### ISSUE TITLE
Support taking UDT as pandas_udf input in Spark

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#121]
Currently, Spark ```@pandas_udf``` does not support UDT for both input and output.

We should contribute to Spark to make the following code feasible.

```
df = spark.createDataFrame([Row(id=1, img=Image("s3://bucket/foo")), Row(id=2, img=Image("s3://bucket/foo"))]

@pandas_udf(ArrayType(StructType([
    StructField("score", FloatType()),
    StructField("box", Box2dType()),
    StructField("label", IntegerType()),
])))
def object_detection(iter: Iterator[pd.Series]) -> Iterator[pd.Series]:
    model = mlflow.pytorch.load_model("model://..../yolo")
    for series in iter:
         dataset = rikai.torch.SeriesDataset(series, batch=16)
         output_series = []
         for batch in dataset:
              predictions = model(batch)
              output_series.extend(predictions)
         yield output_series

df = df.withColumns("predictions", object_detection(df.image))
df.write.format("rikai").save("s3://to/results")f
```

**Comment by eddyxu** [comment]
The first task is be able to pass UDT (i.e., ImageType) into the pandas udf (i.e., `object_detection`)

**Comment by eddyxu** [comment]
https://github.com/apache/spark/pull/31735 is on returning UDT from pandas.  Would appreciate to help it moving forward.

**Comment by sadhen** [comment]
I will create a pull request to https://github.com/eddyxu/spark/tree/lei/pandas_udf.

**Comment by sadhen** [comment]
python version: 3.7.10
```
$ pip freeze
certifi==2020.12.5
numpy==1.20.1
pandas==1.1.4
pyarrow==2.0.0
python-dateutil==2.8.1
pytz==2021.1
scipy==1.6.1
six==1.15.0
xmlrunner==1.7.7
```

one of the error msgs of `python/run-tests --testnames pyspark.sql.tests.test_pandas_udf_scalar`

```
======================================================================
ERROR [0.326s]: test_vectorized_udf_varargs (pyspark.sql.tests.test_pandas_udf_scalar.ScalarPandasUDFTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/da/github/apache/spark/python/pyspark/sql/tests/test_pandas_udf_scalar.py", line 588, in test_vectorized_udf_varargs
    self.assertEqual(df.collect(), res.collect())
  File "/Users/da/github/apache/spark/python/pyspark/sql/dataframe.py", line 679, in collect
    sock_info = self._jdf.collectToPython()
  File "/Users/da/github/apache/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/da/github/apache/spark/python/pyspark/sql/utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.PythonException:
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/Users/da/github/apache/spark/python/lib/pyspark.zip/pyspark/worker.py", line 601, in main
    process()
  File "/Users/da/github/apache/spark/python/lib/pyspark.zip/pyspark/worker.py", line 593, in process
    serializer.dump_stream(out_iter, outfile)
  File "/Users/da/github/apache/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 290, in dump_stream
    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)
  File "/Users/da/github/apache/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 83, in dump_stream
    for batch in iterator:
  File "/Users/da/github/apache/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 284, in init_stream_yield_batches
    batch = self._create_batch(series)
  File "/Users/da/github/apache/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 226, in _create_batch
    arrs.append(create_array(s, dt, t))
  File "/Users/da/github/apache/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 184, in create_array
    array = pa.Array.from_pandas(s, mask=mask, type=t, safe=self._safecheck)
  File "pyarrow/array.pxi", line 887, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 292, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 107, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Did not pass numpy.dtype object
```

**Comment by sadhen** [comment]
Switched to Python 3.8.8, and all of `python/run-tests --testnames pyspark.sql.tests.test_pandas_udf_scalar` passed.

**Comment by sadhen** [comment]
For Apache Spark, from https://github.com/apache/spark/blob/master/.github/workflows/build_and_test.yml

Only Python 3.6 and 3.8 is tested in Github Action.

**Comment by sadhen** [comment]
A bit confused, I can't find the output even with the `--verbose` option.

```
(spark) ➜  spark git:(da/pandas_udf) python/run-tests --verbose --testnames pyspark.sql.tests.test_pandas_udf_scalar
Running PySpark tests. Output is in /Users/da/github/apache/spark/python/unit-tests.log
Will test against the following Python executables: ['/Users/da/opt/miniconda3/envs/spark/bin/python3']
Will test the following Python tests: ['pyspark.sql.tests.test_pandas_udf_scalar']
/Users/da/opt/miniconda3/envs/spark/bin/python3 python_implementation is CPython
/Users/da/opt/miniconda3/envs/spark/bin/python3 version is: Python 3.8.8
Starting test(/Users/da/opt/miniconda3/envs/spark/bin/python3): pyspark.sql.tests.test_pandas_udf_scalar
Finished test(/Users/da/opt/miniconda3/envs/spark/bin/python3): pyspark.sql.tests.test_pandas_udf_scalar (36s)
Tests passed in 36 seconds
(spark) ➜  spark git:(da/pandas_udf) stat /Users/da/github/apache/spark/python/unit-tests.log
stat: cannot stat '/Users/da/github/apache/spark/python/unit-tests.log': No such file or directory
```

**Comment by sadhen** [comment]
A WIP PR is created: https://github.com/eddyxu/spark/pull/1

I need more time to review the python part of the original PR. And move it forward.

**Comment by eddyxu** [comment]
No worries, please take your time @sadhen !  And thank you so much for taking care of this issue.

**Comment by sadhen** [comment]
@eddyxu  IMHO, https://github.com/apache/spark/pull/31735 is too big to review.

How about splitting it into several PRs to Apache Spark.

1. Support UDT for DataFrame in PySpark
2. UDT input for pandas_udf
3. UDT output for pandas_udf

**Comment by eddyxu** [comment]
That makes total senses.  @sadhen . Thank you for owning it!

**Comment by sadhen** [comment]
Just improved https://github.com/eddyxu/spark/pull/2

Still need to add more unit tests, and I think this PR is ready to review and merge.

If you think it's ok, please merge it and change the title of https://github.com/apache/spark/pull/31735: from `SPARK-34600` to `SPARK-34771`， and let the Spark community do another round of code review.

Otherwise, let me add more tests and make more improvements according to your code review comments.

**Comment by sadhen** [comment]
Let me create another PR to make PyLint happy.

**Comment by sadhen** [comment]
Make PyLint Happy: https://github.com/eddyxu/spark/pull/3

**Comment by sadhen** [comment]
Support for TimestampType in UDT is tricky and a common problem for [SPARK-34600](https://issues.apache.org/jira/browse/SPARK-34600).

I plan to work on [SPARK-34771](https://issues.apache.org/jira/browse/SPARK-34771) first and then handle the corner cases.

**Comment by PerilousApricot** [comment]
Hi @sadhen -- I've tried to follow the different PRs and JIRAs, so forgive me if I've missed it. Do you think at some point this work will support Pandas' [extension](https://pandas.pydata.org/pandas-docs/stable/development/extending.html) API to enable exposing these UDTs to pandas without needing an intermediate conversion?
