### ISSUE TITLE
Create a notebook for SQL ML capability

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#186]

**Comment by da-tubi** [comment]
Can I create a dummy model?
``` python
$ pyspark --conf spark.jars.packages=ai.eto:rikai_2.12:0.0.6 --conf spark.sql.extensions=ai.eto.rikai.sql.spark.RikaiSparkSessionExtensions
>>> import rikai
>>> rikai.spark.sql.init(spark)
2021-04-14 22:56:32,462 INFO Rikai (callback_service.py:33): Spark callback server started
2021-04-14 22:56:32,469 INFO Rikai (callback_service.py:91): Rikai Python CallbackService is registered to SparkSession
>>> spark.sql("CREATE MODEL test_empty USING '/tmp/empty_model_not_exist'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/sql/session.py", line 723, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o30.sql.
: ai.eto.rikai.sql.model.ModelResolveException: Model registry schema 'null' is not supported
	at ai.eto.rikai.sql.model.Registry$.resolve(Registry.scala:136)
	at ai.eto.rikai.sql.spark.execution.CreateModelCommand.run(CreateModelCommand.scala:42)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:228)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:228)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:615)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:610)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

>>> spark.sql("CREATE MODEL test_empty USING 'file:///tmp/empty_model_not_exist'")
2021-04-14 22:56:49,360 INFO Rikai (fs.py:110): Resolving model test_empty from file:///tmp/empty_model_not_exist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/sql/session.py", line 723, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o30.sql.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 2442, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/rikai/spark/sql/callback_service.py", line 85, in resolve
    return registry.resolve(uri, name, options)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/rikai/spark/sql/codegen/fs.py", line 114, in resolve
    raise ValueError(f"Model URI is not supported: {uri}")
ValueError: Model URI is not supported: file:///tmp/empty_model_not_exist

	at py4j.Protocol.getReturnValue(Protocol.java:476)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:108)
	at com.sun.proxy.$Proxy17.resolve(Unknown Source)
	at ai.eto.rikai.sql.spark.Python$.resolve(Python.scala:75)
	at ai.eto.rikai.sql.model.fs.FileSystemRegistry.resolve(FileSystemRegistry.scala:50)
	at ai.eto.rikai.sql.model.Registry$.resolve(Registry.scala:133)
	at ai.eto.rikai.sql.spark.execution.CreateModelCommand.run(CreateModelCommand.scala:42)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:228)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:228)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:615)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:610)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by da-tubi** [comment]
Works fine now:

``` bash
pyspark \
  --conf spark.jars.packages=ai.eto:rikai_2.12:0.0.6 \
  --conf spark.sql.extensions=ai.eto.rikai.sql.spark.RikaiSparkSessionExtensions \
  --conf rikai.sql.ml.catalog.impl=ai.eto.rikai.sql.model.SimpleCatalog \
  --conf rikai.sql.ml.registry.file.impl=ai.eto.rikai.sql.model.fs.FileSystemRegistry
```

``` python
>>> import rikai
>>> rikai.spark.sql.init(spark)
2021-04-14 23:21:50,930 INFO Rikai (callback_service.py:33): Spark callback server started
2021-04-14 23:21:50,937 INFO Rikai (callback_service.py:91): Rikai Python CallbackService is registered to SparkSession
>>> spark.sql("CREATE MODEL test_empty USING 'file:///tmp/empty_model_not_exist.yml'")
2021-04-14 23:21:53,411 INFO Rikai (fs.py:110): Resolving model test_empty from file:///tmp/empty_model_not_exist.yml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/sql/session.py", line 723, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o30.sql.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 2442, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/rikai/spark/sql/callback_service.py", line 85, in resolve
    return registry.resolve(uri, name, options)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/rikai/spark/sql/codegen/fs.py", line 112, in resolve
    func_name = codegen_from_yaml(self._spark, uri, name, options)
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/rikai/spark/sql/codegen/fs.py", line 93, in codegen_from_yaml
    with open_uri(uri) as fobj:
  File "/Users/da/opt/miniconda3/envs/rikai-v0.0.6/lib/python3.8/site-packages/rikai/io.py", line 160, in open_uri
    return filesystem.open_input_file(path)
  File "pyarrow/_fs.pyx", line 587, in pyarrow._fs.FileSystem.open_input_file
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/tmp/empty_model_not_exist.yml'. Detail: [errno 2] No such file or directory

	at py4j.Protocol.getReturnValue(Protocol.java:476)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:108)
	at com.sun.proxy.$Proxy17.resolve(Unknown Source)
	at ai.eto.rikai.sql.spark.Python$.resolve(Python.scala:75)
	at ai.eto.rikai.sql.model.fs.FileSystemRegistry.resolve(FileSystemRegistry.scala:50)
	at ai.eto.rikai.sql.model.Registry$.resolve(Registry.scala:133)
	at ai.eto.rikai.sql.spark.execution.CreateModelCommand.run(CreateModelCommand.scala:42)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:228)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:228)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:615)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:610)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by eddyxu** [comment]
We should provide a "default" registry, that can fallback to it if no scheme is found from uri

**Comment by eddyxu** [comment]
@da-tubi you can create a dummy model using `TestRegistry`

https://github.com/eto-ai/rikai/blob/master/python/tests/spark/test_code_gen.py#L22-L24

**Comment by darcy-shen** [comment]
See #500
