### ISSUE TITLE
sbt failed

### ISSUE THREAD

**Issue by sadhen** [eto-ai/rikai#195]
```
(rikai) ➜  rikai git:(master) sbt
[info] welcome to sbt 1.4.4 (AdoptOpenJDK Java 1.8.0_252)
[info] loading settings for project global-plugins from plugins.sbt ...
[info] loading global plugins from /Users/da/.sbt/1.0/plugins
[info] loading settings for project rikai-build from plugins.sbt,sbt-antlr4.sbt ...
[info] loading project definition from /Users/da/github/eto-ai/rikai/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] loading settings for project rikai from build.sbt ...
scala.MatchError: List(9796470b) (of class scala.collection.immutable.$colon$colon)
	at $fcb942abbe65825492e6$.versionFmt(build.sbt:6)
	at $30bb00ecdee69541f9f3$.$anonfun$$sbtdef$6(/Users/da/github/eto-ai/rikai/build.sbt:33)
	at scala.Option.fold(Option.scala:251)
	at sbtdynver.GitDescribeOutput$OptGitDescribeOutputOps$.mkVersion$extension(DynVerPlugin.scala:189)
	at $30bb00ecdee69541f9f3$.$anonfun$$sbtdef$5(/Users/da/github/eto-ai/rikai/build.sbt:33)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] scala.MatchError: List(9796470b) (of class scala.collection.immutable.$colon$colon)
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by sadhen** [comment]
```
git fetch origin
```

Fetch the tags and it can be fixed.
