### ISSUE TITLE
Resource leak in test

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/rikai#209]
```
[warn] Thread[Thread-20,5,main] loading org.apache.hadoop.util.ShutdownHookManager$2 after test or run has completed. This is a likely resource leak
Exception in thread "Thread-20" java.lang.IllegalAccessError: failed to access class org.apache.hadoop.util.ShutdownHookManager$2 from class org.apache.hadoop.util.ShutdownHookManager (org.apache.hadoop.util.ShutdownHookManager$2 is in unnamed module of loader sbt.internal.ManagedClassLoader$ZombieClassLoader @354de1cc; org.apache.hadoop.util.ShutdownHookManager is in unnamed module of loader sbt.internal.LayeredClassLoader @60d5eb2b)
        at org.apache.hadoop.util.ShutdownHookManager.getShutdownHooksInOrder(ShutdownHookManager.java:273)
	at org.apache.hadoop.util.ShutdownHookManager.executeShutdown(ShutdownHookManager.java:121)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:95)
```

**Comment by changhiskhan** [comment]
don't see it anymore i think
