### ISSUE TITLE
failed to `show models` with java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by da-tubi** [eto-ai/rikai#312]
Databricks 8.4 (Apache Spark 3.1.2)
Rikai 0.0.9

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-2921603913019507> in <module>
----> 1 spark.sql("show models").show(1, vertical=False, truncate=False)

/databricks/spark/python/pyspark/sql/session.py in sql(self, sqlQuery)
    775         [Row(f1=1, f2='row1'), Row(f1=2, f2='row2'), Row(f1=3, f2='row3')]
    776         """
--> 777         return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
    778 
    779     def table(self, tableName):

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o259.sql.
: java.lang.AbstractMethodError: Method ai/eto/rikai/sql/spark/execution/ShowModelsCommand.org$apache$spark$sql$catalyst$plans$logical$Command$_setter_$nodePatterns_$eq(Lscala/collection/Seq;)V is abstract
	at ai.eto.rikai.sql.spark.execution.ShowModelsCommand.org$apache$spark$sql$catalyst$plans$logical$Command$_setter_$nodePatterns_$eq(ShowModelsCommand.scala)
	at org.apache.spark.sql.catalyst.plans.logical.Command.$init$(Command.scala:39)
	at ai.eto.rikai.sql.spark.execution.ShowModelsCommand.<init>(ShowModelsCommand.scala:23)
	at ai.eto.rikai.sql.spark.parser.RikaiExtAstBuilder.visitShowModels(RikaiExtAstBuilder.scala:146)
	at ai.eto.rikai.sql.spark.parser.RikaiExtAstBuilder.visitShowModels(RikaiExtAstBuilder.scala:36)
	at ai.eto.rikai.sql.spark.parser.RikaiExtSqlBaseParser$ShowModelsContext.accept(RikaiExtSqlBaseParser.java:217)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at ai.eto.rikai.sql.spark.parser.RikaiExtAstBuilder.$anonfun$visitSingleStatement$1(RikaiExtAstBuilder.scala:41)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:124)
	at ai.eto.rikai.sql.spark.parser.RikaiExtAstBuilder.visitSingleStatement(RikaiExtAstBuilder.scala:41)
	at ai.eto.rikai.sql.spark.parser.RikaiExtAstBuilder.visitSingleStatement(RikaiExtAstBuilder.scala:36)
	at ai.eto.rikai.sql.spark.parser.RikaiExtSqlBaseParser$SingleStatementContext.accept(RikaiExtSqlBaseParser.java:133)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at ai.eto.rikai.sql.spark.parser.RikaiExtSqlParser.$anonfun$parsePlan$1(RikaiExtSparkSQLParser.scala:68)
	at ai.eto.rikai.sql.spark.parser.RikaiExtSqlParser.parse(RikaiExtSparkSQLParser.scala:101)
	at ai.eto.rikai.sql.spark.parser.RikaiExtSqlParser.parsePlan(RikaiExtSparkSQLParser.scala:66)
	at com.databricks.sql.parser.DatabricksSqlParser.$anonfun$parsePlan$1(DatabricksSqlParser.scala:67)
	at com.databricks.sql.parser.DatabricksSqlParser.parse(DatabricksSqlParser.scala:87)
	at com.databricks.sql.parser.DatabricksSqlParser.parsePlan(DatabricksSqlParser.scala:64)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:685)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:134)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:685)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:852)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:682)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by da-tubi** [comment]
Here is the related PR: https://github.com/apache/spark/pull/32686

It seems Databricks backported this PR to 3.1.2.

**Comment by eddyxu** [comment]
Could you elaborate a bit, is there any action item from us?

**Comment by da-tubi** [comment]
Wait for the next release of Apache Spark (3.2.0), and then fix this issue.
