### ISSUE TITLE
Failed to run `sbt test` on intel mac

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#313]
```
[error] Uncaught exception when running ai.eto.rikai.sql.spark.execution.CreateModelCommandTest: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.SparkConf$
[error] sbt.ForkMain$ForkError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.SparkConf$
[error] 	at org.apache.spark.SparkConf.set(SparkConf.scala:94)
[error] 	at org.apache.spark.SparkConf.set(SparkConf.scala:83)
[error] 	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$1(SparkSession.scala:916)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
[error] 	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:916)
```

OSX 11.5.2

**Comment by da-tubi** [comment]
Works fine for me. 

+ macOS 10.15.7
+ Java OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)

**Comment by eddyxu** [comment]
Hmm, my sbt was installed via `homebrew`, which uses jdk 16.

After setting JAVA_HOME, it works fine now.
