### ISSUE TITLE
output_schema cannot be `array<struct<box:array<float>, score:float, label_ids:int>>`

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#333]
Because PySpark Pandas UDF does not support it.

```
Traceback (most recent call last):
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/rikai/spark/sql/callback_service.py", line 103, in resolve
    return registry.resolve(spec)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/rikai/spark/sql/codegen/mlflow_registry.py", line 240, in resolve
    func_name = codegen_from_spec(self._spark, spec, name)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/rikai/spark/sql/codegen/mlflow_registry.py", line 191, in codegen_from_spec
    udf = udf_from_spec(spec)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/rikai/spark/sql/codegen/base.py", line 188, in udf_from_spec
    return generate_udf(spec)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/rikai/spark/sql/codegen/pytorch.py", line 85, in generate_udf
    return pandas_udf(torch_inference_udf, returnType=schema)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/pandas/functions.py", line 377, in pandas_udf
    return _create_pandas_udf(f=f, returnType=return_type, evalType=eval_type)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/pandas/functions.py", line 432, in _create_pandas_udf
    return _create_udf(f, returnType, evalType)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/udf.py", line 43, in _create_udf
    return udf_obj._wrapped()
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/udf.py", line 206, in _wrapped
    wrapper.returnType = self.returnType
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/udf.py", line 103, in returnType
    raise NotImplementedError(
NotImplementedError: Invalid return type with scalar Pandas UDFs: ArrayType(StructType(List(StructField(box,ArrayType(FloatType,true),true),StructField(score,FloatType,true),StructField(label_ids,IntegerType,true))),true) is not supported
```

**Comment by darcy-shen** [comment]
Here is the root cause:

https://github.com/apache/spark/blob/de351e30a90dd988b133b3d00fa6218bfcaba8b8/python/pyspark/sql/pandas/types.py#L58-L61
