### ISSUE TITLE
NoSuchMethodError: UnresolvedFunction

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#415]
Rikai 0.0.15 when using ML_PREDICT in SQL
```
Py4JJavaError: An error occurred while calling o38.sql.
: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.UnresolvedFunction$.apply(Lorg/apache/spark/sql/catalyst/FunctionIdentifier;Lscala/collection/Seq;Z)Lorg/apache/spark/sql/catalyst/analysis/UnresolvedFunction;
	at ai.eto.rikai.sql.model.SparkUDFModel.asSpark(Model.scala:98)
	at ai.eto.rikai.sql.spark.parser.RikaiSparkSQLAstBuilder.$anonfun$visitMlPredictFunction$1(RikaiSparkSQLAstBuilder.scala:78)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:124)
	at ai.eto.rikai.sql.spark.parser.RikaiSparkSQLAstBuilder.visitMlPredictFunction(RikaiSparkSQLAstBuilder.scala:53)
	at ai.eto.rikai.sql.spark.parser.RikaiSparkSQLAstBuilder.$anonfun$visitFunctionCall$1(RikaiSparkSQLAstBuilder.scala:45)
```

Found when I'm trying Rikai 0.0.15: https://github.com/da-tubi/rikai-example/pull/8

**Comment by darcy-shen** [comment]
Full stacktrace:

```
(rikai-example) ➜  rikai-example git:(upgrade/rikai_0.0.15) ✗ python
Python 3.8.10 (default, May 19 2021, 11:01:55)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from example import spark

:: loading settings :: url = jar:file:/Users/da/.pyenv/versions/3.8.10/envs/rikai-example/lib/python3.8/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /Users/da/.ivy2/cache
The jars for the packages stored in: /Users/da/.ivy2/jars
ai.eto#rikai_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-d39c2967-d532-48a7-8148-c4e357d75c7d;1.0
	confs: [default]
	found ai.eto#rikai_2.12;0.0.15 in central
	found org.antlr#antlr4-runtime;4.8-1 in local-m2-cache
	found org.xerial.snappy#snappy-java;1.1.8.4 in central
	found com.typesafe.scala-logging#scala-logging_2.12;3.9.4 in central
	found org.scala-lang#scala-reflect;2.12.13 in spark-list
	found org.slf4j#slf4j-api;1.7.30 in spark-list
	found io.circe#circe-core_2.12;0.12.3 in central
	found io.circe#circe-numbers_2.12;0.12.3 in central
	found org.typelevel#cats-core_2.12;2.0.0 in central
	found org.typelevel#cats-macros_2.12;2.0.0 in central
	found org.typelevel#cats-kernel_2.12;2.0.0 in central
	found io.circe#circe-generic_2.12;0.12.3 in central
	found com.chuusai#shapeless_2.12;2.3.3 in spark-list
	found org.typelevel#macro-compat_2.12;1.1.1 in spark-list
	found io.circe#circe-parser_2.12;0.12.3 in central
	found io.circe#circe-jawn_2.12;0.12.3 in central
	found org.typelevel#jawn-parser_2.12;0.14.2 in central
	found org.mlflow#mlflow-client;1.21.0 in central
	found com.thoughtworks.enableIf#enableif_2.12;1.1.7 in central
	found org.apache.logging.log4j#log4j-core;2.17.0 in central
:: resolution report :: resolve 382ms :: artifacts dl 15ms
	:: modules in use:
	ai.eto#rikai_2.12;0.0.15 from central in [default]
	com.chuusai#shapeless_2.12;2.3.3 from spark-list in [default]
	com.thoughtworks.enableIf#enableif_2.12;1.1.7 from central in [default]
	com.typesafe.scala-logging#scala-logging_2.12;3.9.4 from central in [default]
	io.circe#circe-core_2.12;0.12.3 from central in [default]
	io.circe#circe-generic_2.12;0.12.3 from central in [default]
	io.circe#circe-jawn_2.12;0.12.3 from central in [default]
	io.circe#circe-numbers_2.12;0.12.3 from central in [default]
	io.circe#circe-parser_2.12;0.12.3 from central in [default]
	org.antlr#antlr4-runtime;4.8-1 from local-m2-cache in [default]
	org.apache.logging.log4j#log4j-core;2.17.0 from central in [default]
	org.mlflow#mlflow-client;1.21.0 from central in [default]
	org.scala-lang#scala-reflect;2.12.13 from spark-list in [default]
	org.slf4j#slf4j-api;1.7.30 from spark-list in [default]
	org.typelevel#cats-core_2.12;2.0.0 from central in [default]
	org.typelevel#cats-kernel_2.12;2.0.0 from central in [default]
	org.typelevel#cats-macros_2.12;2.0.0 from central in [default]
	org.typelevel#jawn-parser_2.12;0.14.2 from central in [default]
	org.typelevel#macro-compat_2.12;1.1.1 from spark-list in [default]
	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
	:: evicted modules:
	org.slf4j#slf4j-api;1.7.25 by [org.slf4j#slf4j-api;1.7.30] in [default]
	org.scala-lang#scala-reflect;2.12.6 by [org.scala-lang#scala-reflect;2.12.13] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   22  |   0   |   0   |   2   ||   20  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-d39c2967-d532-48a7-8148-c4e357d75c7d
	confs: [default]
	0 artifacts copied, 20 already retrieved (0kB/12ms)
21/12/27 11:54:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2021-12-27 11:54:30,866 INFO Rikai (callback_service.py:54): Spark callback server started
2021-12-27 11:54:30,876 INFO Rikai (callback_service.py:113): Rikai Python CallbackService is registered to SparkSession
>>>
>>> from rikai.contrib.yolov5.transforms import OUTPUT_SCHEMA

spark.sql(f"""
CREATE MODEL yolov5s
FLAVOR yolov5
PREPROCESSOR 'rikai.contrib.yolov5.transforms.pre_processing'
POSTPROCESSOR 'rikai.contrib.yolov5.transforms.post_processing'
OPTIONS (device="cpu", batch_size=32)
RETURNS {OUTPUT_SCHEMA}
USING "torchhub:///ultralytics/yolov5:v6.0/yolov5s";
""")
>>>
>>> spark.sql(f"""
... CREATE MODEL yolov5s
... FLAVOR yolov5
... PREPROCESSOR 'rikai.contrib.yolov5.transforms.pre_processing'
... POSTPROCESSOR 'rikai.contrib.yolov5.transforms.post_processing'
... OPTIONS (device="cpu", batch_size=32)
... RETURNS {OUTPUT_SCHEMA}
... USING "torchhub:///ultralytics/yolov5:v6.0/yolov5s";
... """)
2021-12-27 11:54:55,525 INFO Rikai (torchhub_registry.py:62): Resolving model yolov5s from torchhub:///ultralytics/yolov5:v6.0/yolov5s
2021-12-27 11:54:55,640 INFO Rikai (base.py:210): Created model inference pandas_udf with name yolov5s_f7db4aa6
DataFrame[]
>>> spark.sql("select ML_PREDICT(yolov5s, 'path/to/lena.png')")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/session.py", line 723, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o38.sql.
: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.UnresolvedFunction$.apply(Lorg/apache/spark/sql/catalyst/FunctionIdentifier;Lscala/collection/Seq;Z)Lorg/apache/spark/sql/catalyst/analysis/UnresolvedFunction;
	at ai.eto.rikai.sql.model.SparkUDFModel.asSpark(Model.scala:98)
```

**Comment by darcy-shen** [comment]
See https://github.com/apache/spark/blob/de351e30a90dd988b133b3d00fa6218bfcaba8b8/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/unresolved.scala#L262

It seems that it is a Scala language issue.

**Comment by changhiskhan** [comment]
Was it introduced recently? Any possibly of bisecting ?

**Comment by darcy-shen** [comment]
I guess `org.scala-lang#scala-reflect;2.12.13 from spark-list in [default]` is the root cause.

**Comment by darcy-shen** [comment]
Let me find the root cause greedily.

**Comment by darcy-shen** [comment]
It seems it is https://mvnrepository.com/artifact/com.typesafe.scala-logging/scala-logging_2.12/3.9.4 who evicted the `scala-reflect` library to 2.12.13.

**Comment by darcy-shen** [comment]
Unit tests work fine. This might be a very tricky bug. It might only occurs when we are using Rikai from maven central.

**Comment by darcy-shen** [comment]
Here is a possible fix: https://github.com/eto-ai/rikai/pull/416
I still need to confirm that it really fixed it.

**Comment by darcy-shen** [comment]
ooops, I found that Rikai 0.0.15 depends on Spark 3.2.0

See https://mvnrepository.com/artifact/ai.eto/rikai_2.12/0.0.15

But the rikai python package still stick to Spark 3.1.2.

**Comment by darcy-shen** [comment]
With https://github.com/eto-ai/rikai/pull/337, the default Spark is 3.1.2.

How did we publish rikai to sonatype? Manually or via github action `sbt ci-release`.

**Comment by darcy-shen** [comment]
See https://github.com/eto-ai/rikai/runs/4623698920?check_suite_focus=true

It is a publish issue.
