### ISSUE TITLE
Can not create model in MLflowCatalog

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#493]
```
0: jdbc:hive2://localhost:10001/default> CREATE MODEL ssd1 using "mlflow:/model/ssd"
. . . . . . . . . . . . . . . . . . . .> ;
Error: org.apache.hive.service.cli.HiveSQLException: Error running query: org.mlflow.tracking.MlflowHttpException: statusCode=404 reasonPhrase=[NOT FOUND] bodyMessage=[{"error_code": "RESOURCE_DOES_NOT_EXIST", "message": "Registered Model with name=ssd1 not found"}]
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:361)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:263)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties(SparkOperation.scala:78)
	at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperti
```

**Comment by eddyxu** [comment]
Duplicated to #496
