### ISSUE TITLE
Some pretrained torchvision is only available in torchvision > 0.10.0

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#622]
```
>>> from torchvision.models import efficientnet_b0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'efficientnet_b0' from 'torchvision.models' (/Users/da/.pyenv/versions/rikai/lib/python3.8/site-packages/torchvision/models/__init__.py)
>>> import torchvision
>>> torchvision.__version__
'0.10.0'
```

From [CI](https://github.com/eto-ai/rikai/runs/5968591157?check_suite_focus=true), we can know that torchvision 0.12.0 is the workable version.

We have two choices:
+ Upgrade torchvision
+ Disable the code via `torchvision.__version__`, throw a RuntimeError like `you should use torchvision vx.y.z` would be friendly to user.

**Comment by eddyxu** [comment]
i think it might be easy just bump pytorch and torchvision version

**Comment by darcy-shen** [comment]
```
Python 3.8.10 (default, May 19 2021, 11:01:55)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from torchvision.models import convnext_base
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'convnext_base' from 'torchvision.models' (/Users/da/.pyenv/versions/rikai-yolov5/lib/python3.8/site-packages/torchvision/models/__init__.py)
>>>
```

`from torchvision.models import convnext_base` does not work for `torchvision 0.11.3`, but works fine for `torchvision 0.12.0`.
